language: python
python:
  - "3.6"
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
services:
  - postgresql
before script:
  - psql -c 'create database politicosys_test;' -U
script:
  - python -m pytest --cov=app
  - coveralls
after_success:
  - coverallsv
